"""Shared policy for catalog cards that automated opponents may use.

`Team Of Admins` is intentionally reserved for human/admin-owned content and must
never be selected by a bot, autogenerated opponent lineup, Clan War draft auto-pick,
or other server-side random bot roster generation.
"""

from __future__ import annotations

from typing import Any

BOT_BLOCKED_COLLECTION_NAME = "Team Of Admins"
BOT_BLOCKED_COLLECTION_CODE = "team-of-admins"


def is_bot_card_allowed(row: Any) -> bool:
    """Return False for cards from collections forbidden to automated opponents.

    Supports sqlite rows/dicts/objects that expose collection_name and/or
    collection_code. Matching is case-insensitive and trims surrounding spaces.
    """
    try:
        name = row["collection_name"]
    except (KeyError, IndexError, TypeError):
        name = getattr(row, "collection_name", "")
    try:
        code = row["collection_code"]
    except (KeyError, IndexError, TypeError):
        code = getattr(row, "collection_code", "")

    normalized_name = str(name or "").strip().casefold()
    normalized_code = str(code or "").strip().casefold()
    return (
        normalized_name != BOT_BLOCKED_COLLECTION_NAME.casefold()
        and normalized_code != BOT_BLOCKED_COLLECTION_CODE.casefold()
    )
